#!/usr/bin/env python3
"""
OpenClaw Live Telegram Bot Daemon.
Long-polls Telegram API, enforces whitelist security, calls Gemini API, and returns responses.
"""

import os
import sys
import time
import json
import urllib.request
import urllib.error

TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip()
GEMINI_API_KEY = os.environ.get("GEMINI_API_KEY", "").strip()
ALLOWED_USERS_RAW = os.environ.get("TELEGRAM_ALLOWED_USER_IDS", "").strip()

def parse_allowed_ids(raw):
    if not raw:
        return set()
    return set(x.strip() for x in raw.split(",") if x.strip())

def get_allowed_user_ids():
    raw = os.environ.get("TELEGRAM_ALLOWED_USER_IDS", "").strip()
    return parse_allowed_ids(raw)

def send_telegram_message(chat_id, text):
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip() or TELEGRAM_BOT_TOKEN
    if not token:
        print("[DAEMON ERROR] TELEGRAM_BOT_TOKEN is not set.", flush=True)
        return
    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = json.dumps({"chat_id": chat_id, "text": text}).encode('utf-8')
    req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            pass
    except Exception as e:
        print(f"[DAEMON ERROR] Failed to send message to Telegram chat {chat_id}: {e}", flush=True)

def query_gemini(prompt):
    api_key = os.environ.get("GEMINI_API_KEY", "").strip() or GEMINI_API_KEY
    if not api_key:
        return "Error: GEMINI_API_KEY is not configured on OpenClaw server."
    model = "gemini-2.5-flash"
    url = f"https://generativelanguage.googleapis.com/v1beta/models/{model}:generateContent?key={api_key}"
    payload = json.dumps({
        "contents": [{"parts": [{"text": prompt}]}]
    }).encode('utf-8')
    req = urllib.request.Request(url, data=payload, headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=30) as resp:
            data = json.loads(resp.read().decode('utf-8'))
            candidates = data.get("candidates", [])
            if candidates:
                parts = candidates[0].get("content", {}).get("parts", [])
                text_parts = [p.get("text", "") for p in parts if "text" in p]
                if text_parts:
                    return "".join(text_parts).strip()
            return "No text response generated by Gemini."
    except Exception as e:
        return f"Gemini API Error: {e}"



def process_update(update):
    msg = update.get("message") or update.get("edited_message")
    if not msg:
        return

    chat_id = msg.get("chat", {}).get("id")
    user_id = str(msg.get("from", {}).get("id"))
    text = msg.get("text", "").strip()

    if not text or not chat_id:
        return

    allowed_ids = get_allowed_user_ids()

    # Check Whitelist Access
    if allowed_ids and user_id not in allowed_ids:
        print(f"[DAEMON REJECT] User ID {user_id} not in whitelist {allowed_ids}", flush=True)
        send_telegram_message(chat_id, f"🚫 Access Denied: Telegram User ID {user_id} is not whitelisted on OpenClaw.")
        return

    print(f"[DAEMON AUTH] Processing message from authorized User ID {user_id}: {text}", flush=True)

    if text in ["/start", "/help"]:
        send_telegram_message(chat_id, "🤖 OpenClaw Bot Active!\nSend any message to chat with Gemini AI, or use Workspace commands:\n/calendar - Agenda\n/gmail - Inbox search\n/drive - File search\n/status - System status")
        return
    elif text == "/status":
        send_telegram_message(chat_id, f"✅ OpenClaw Status: Online\nWhitelisted Users: {len(allowed_ids)}\nModel: gemini-2.5-flash\nWorkspace MCP Integration: Active")
        return
    elif text.startswith("/calendar"):
        from tool_gateway import ToolGateway
        gw = ToolGateway()
        res = gw.call_mcp_tool("calendar_list_events")
        events = res.get("output", {}).get("events", [])
        if events:
            lines = ["📅 *Upcoming Calendar Events:*"]
            for ev in events:
                lines.append(f"• *{ev.get('summary')}* ({ev.get('start')} - {ev.get('end')})\n  {ev.get('location', '')}")
            send_telegram_message(chat_id, "\n".join(lines))
        else:
            send_telegram_message(chat_id, "📅 No calendar events found.")
        return
    elif text.startswith("/gmail"):
        from tool_gateway import ToolGateway
        gw = ToolGateway()
        query = text[7:].strip() or "is:unread"
        res = gw.call_mcp_tool("gmail_search", json.dumps({"query": query}))
        msgs = res.get("output", {}).get("messages", [])
        if msgs:
            lines = [f"📧 *Gmail Search Results ('{query}'):*"]
            for m in msgs:
                lines.append(f"• *From:* {m.get('from')}\n  *Subject:* {m.get('subject')}\n  _{m.get('snippet')}_")
            send_telegram_message(chat_id, "\n".join(lines))
        else:
            send_telegram_message(chat_id, f"📧 No messages found for query '{query}'.")
        return
    elif text.startswith("/drive"):
        from tool_gateway import ToolGateway
        gw = ToolGateway()
        query = text[6:].strip() or "OpenClaw"
        res = gw.call_mcp_tool("drive_search_files", json.dumps({"query": query}))
        files = res.get("output", {}).get("files", [])
        if files:
            lines = [f"📁 *Drive Search Results ('{query}'):*"]
            for f in files:
                lines.append(f"• *{f.get('name')}* ({f.get('mimeType')})\n  Link: {f.get('webViewLink')}")
            send_telegram_message(chat_id, "\n".join(lines))
        else:
            send_telegram_message(chat_id, f"📁 No files found for query '{query}'.")
        return

    # Query Gemini and reply
    answer = query_gemini(text)
    send_telegram_message(chat_id, answer)

def main():
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip() or TELEGRAM_BOT_TOKEN
    if not token:
        print("[DAEMON FATAL] Missing TELEGRAM_BOT_TOKEN.", flush=True)
        sys.exit(1)

    allowed_ids = get_allowed_user_ids()
    print(f"[DAEMON START] Telegram Bot Daemon running with {len(allowed_ids)} whitelisted users.", flush=True)
    offset = 0

    while True:
        try:
            token = os.environ.get("TELEGRAM_BOT_TOKEN", "").strip() or TELEGRAM_BOT_TOKEN
            url = f"https://api.telegram.org/bot{token}/getUpdates?offset={offset}&timeout=20"
            req = urllib.request.Request(url)
            with urllib.request.urlopen(req, timeout=30) as resp:
                data = json.loads(resp.read().decode('utf-8'))
                if data.get("ok"):
                    for update in data.get("result", []):
                        offset = update.get("update_id", 0) + 1
                        process_update(update)
        except Exception as e:
            print(f"[DAEMON POLL WARNING] Error during poll: {e}", flush=True)
            time.sleep(3)

if __name__ == "__main__":
    main()
